In [149]:
# read the data
import pandas as pd


import mne
import os

import ast
import sys
from mne_bids import BIDSPath, write_raw_bids

In [150]:
import pandas as pd
# REname Channel
che_info= pd.read_excel(r'C:\Users\PRAKASH\OneDrive - IIT Delhi\IIT D PhD\Research work\Smartphone addiction\EEG_electrode_naming_issue\New_ch_name.xlsx')
dict(che_info[['Name','actual name']])

chan_rename =dict(zip(che_info['Name'], che_info['actual name']))
chan_rename = dict(list(chan_rename.items())[:-2])

### Create BIDS format data

In [154]:
data_folder = r"D:\Work_data\Notification_evoked_response\Data_at_IITD/"
subjects = [sub for sub in os.listdir(data_folder) if (("SD" in sub) & (os.path.isdir(os.path.join(data_folder,sub))))]
data_type = "EEG"



# Paths
root_dir = r'D:\Work_data\Notification_evoked_response\Data_at_IITD/'       # Directory with your original folders like ET001_SD043
bids_root = r'D:\Work_data\Notification_evoked_response\Data_at_IITD/bids_data'     # Where BIDS output will go
task = 'auditoryoddball'               # task name

# Get all subject folders and sort for consistent numbering
subject_folders = sorted([f for f in os.listdir(root_dir) if os.path.isdir(os.path.join(root_dir, f))])




for sub in subjects:
    path = os.path.join(data_folder,sub,data_type) 
    print(path)    
    for eeg in os.listdir(path):
        print(eeg)
        if eeg[-5:] == ".vhdr":
           
            raw = mne.io.read_raw_brainvision(os.path.join(path,eeg), preload=True)
            raw.rename_channels(chan_rename )
            raw = mne.add_reference_channels(raw, ref_channels=["Cz"])
            raw.set_montage("easycap-M1")
            events,event_dict = mne.events_from_annotations(raw)
            #raw.plot(scalings=dict(eeg=40e-6),clipping='transparent',duration=30.0, start=690.0, n_channels=63,color = "Blue",event_color ='black',show_options=True )
            # Generate BIDS-style subject ID: sub01, sub02, ...
            subj_id = sub.lower()  # 2-digit numbering
            print(subj_id)
            print(subj_id)
            bids_subj_id = f"{subj_id}"
            # Create BIDS path
            bids_path = BIDSPath(subject=bids_subj_id, task=task, root=bids_root, datatype='eeg',
                         suffix='eeg', extension='.vhdr')
            # Write to BIDS
            write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
            print(f"Converted {data_folder} → sub-{bids_subj_id}") # it is useful to scroll eeg data

D:\Work_data\Notification_evoked_response\Data_at_IITD/SD011\EEG
sub011.eeg
sub011.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD011\EEG\sub011.vhdr...
Setting channel info structure...
Reading 0 ... 2431779  =      0.000 ...  2431.779 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd011
sd011
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd011/eeg/sub-sd011_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd011/eeg/sub-sd011_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd011\eeg\sub-sd011_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd011\eeg\sub-sd011_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd011\eeg\sub-sd011_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd011\eeg\sub-sd011_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd011_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd011\sub-sd011_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd011\sub-sd011_scans.tsv entry with eeg\sub-sd011_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd011
sub011.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD012\EEG
SD012.eeg
SD012.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD012\EEG\SD012.vhdr...
Setting channel info structure...
Reading 0 ... 2382059  =      0.000 ...  2382.059 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd012
sd012
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd012/eeg/sub-sd012_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd012/eeg/sub-sd012_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd012\eeg\sub-sd012_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd012\eeg\sub-sd012_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd012\eeg\sub-sd012_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd012\eeg\sub-sd012_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd012_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd012\sub-sd012_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd012\sub-sd012_scans.tsv entry with eeg\sub-sd012_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd012
SD012.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD013\EEG
SD013.eeg
SD013.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD013\EEG\SD013.vhdr...
Setting channel info structure...
Reading 0 ... 2438619  =      0.000 ...  2438.619 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd013
sd013
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd013/eeg/sub-sd013_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd013/eeg/sub-sd013_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd013\eeg\sub-sd013_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd013\eeg\sub-sd013_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd013\eeg\sub-sd013_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd013\eeg\sub-sd013_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd013_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd013\sub-sd013_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd013\sub-sd013_scans.tsv entry with eeg\sub-sd013_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd013
SD013.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD014\EEG
SD014.eeg
SD014.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD014\EEG\SD014.vhdr...
Setting channel info structure...
Reading 0 ... 2368619  =      0.000 ...  2368.619 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd014
sd014
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd014/eeg/sub-sd014_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd014/eeg/sub-sd014_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd014\eeg\sub-sd014_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd014\eeg\sub-sd014_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd014\eeg\sub-sd014_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd014\eeg\sub-sd014_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd014_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd014\sub-sd014_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd014\sub-sd014_scans.tsv entry with eeg\sub-sd014_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd014
SD014.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD015\EEG
SD015.eeg
SD015.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD015\EEG\SD015.vhdr...
Setting channel info structure...
Reading 0 ... 2371899  =      0.000 ...  2371.899 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd015
sd015
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd015/eeg/sub-sd015_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd015/eeg/sub-sd015_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd015\eeg\sub-sd015_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd015\eeg\sub-sd015_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd015\eeg\sub-sd015_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd015\eeg\sub-sd015_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd015_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd015\sub-sd015_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd015\sub-sd015_scans.tsv entry with eeg\sub-sd015_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd015
SD015.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD016\EEG
SD016.eeg
SD016.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD016\EEG\SD016.vhdr...
Setting channel info structure...
Reading 0 ... 2359659  =      0.000 ...  2359.659 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd016
sd016
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd016/eeg/sub-sd016_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd016/eeg/sub-sd016_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd016\eeg\sub-sd016_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd016\eeg\sub-sd016_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd016\eeg\sub-sd016_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd016\eeg\sub-sd016_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd016_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd016\sub-sd016_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd016\sub-sd016_scans.tsv entry with eeg\sub-sd016_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd016
SD016.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD017\EEG
SD017.eeg
SD017.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD017\EEG\SD017.vhdr...
Setting channel info structure...
Reading 0 ... 2283419  =      0.000 ...  2283.419 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 24', 'Stimulus/S 25']
sd017
sd017
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd017/eeg/sub-sd017_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd017/eeg/sub-sd017_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd017\eeg\sub-sd017_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd017\eeg\sub-sd017_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd017\eeg\sub-sd017_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd017\eeg\sub-sd017_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd017_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd017\sub-sd017_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd017\sub-sd017_scans.tsv entry with eeg\sub-sd017_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd017
SD017.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD018\EEG
SD018.eeg
SD018.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD018\EEG\SD018.vhdr...
Setting channel info structure...
Reading 0 ... 2414859  =      0.000 ...  2414.859 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd018
sd018
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd018/eeg/sub-sd018_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd018/eeg/sub-sd018_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd018\eeg\sub-sd018_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd018\eeg\sub-sd018_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd018\eeg\sub-sd018_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd018\eeg\sub-sd018_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd018_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd018\sub-sd018_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd018\sub-sd018_scans.tsv entry with eeg\sub-sd018_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd018
SD018.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD019\EEG
SD019.eeg
SD019.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD019\EEG\SD019.vhdr...
Setting channel info structure...
Reading 0 ... 2360359  =      0.000 ...  2360.359 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd019
sd019
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd019/eeg/sub-sd019_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd019/eeg/sub-sd019_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd019\eeg\sub-sd019_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd019\eeg\sub-sd019_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd019\eeg\sub-sd019_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd019\eeg\sub-sd019_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd019_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd019\sub-sd019_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd019\sub-sd019_scans.tsv entry with eeg\sub-sd019_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd019
SD019.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD020\EEG
SD020.eeg
SD020.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD020\EEG\SD020.vhdr...
Setting channel info structure...
Reading 0 ... 2535859  =      0.000 ...  2535.859 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S255']
sd020
sd020
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd020/eeg/sub-sd020_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd020/eeg/sub-sd020_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S255']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd020\eeg\sub-sd020_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd020\eeg\sub-sd020_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd020\eeg\sub-sd020_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd020\eeg\sub-sd020_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd020_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd020\sub-sd020_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd020\sub-sd020_scans.tsv entry with eeg\sub-sd020_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd020
SD020.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD021\EEG
SD021.eeg
SD021.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD021\EEG\SD021.vhdr...
Setting channel info structure...
Reading 0 ... 2422699  =      0.000 ...  2422.699 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd021
sd021
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd021/eeg/sub-sd021_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd021/eeg/sub-sd021_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd021\eeg\sub-sd021_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd021\eeg\sub-sd021_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd021\eeg\sub-sd021_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd021\eeg\sub-sd021_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd021_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd021\sub-sd021_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd021\sub-sd021_scans.tsv entry with eeg\sub-sd021_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd021
SD021.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD022\EEG
SD022.eeg
SD022.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD022\EEG\SD022.vhdr...
Setting channel info structure...
Reading 0 ... 2361559  =      0.000 ...  2361.559 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd022
sd022
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd022/eeg/sub-sd022_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd022/eeg/sub-sd022_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd022\eeg\sub-sd022_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd022\eeg\sub-sd022_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd022\eeg\sub-sd022_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd022\eeg\sub-sd022_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd022_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd022\sub-sd022_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd022\sub-sd022_scans.tsv entry with eeg\sub-sd022_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd022
SD022.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD023\EEG
SD023.eeg
SD023.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD023\EEG\SD023.vhdr...
Setting channel info structure...
Reading 0 ... 2398319  =      0.000 ...  2398.319 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd023
sd023
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd023/eeg/sub-sd023_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd023/eeg/sub-sd023_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd023\eeg\sub-sd023_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd023\eeg\sub-sd023_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd023\eeg\sub-sd023_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd023\eeg\sub-sd023_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd023_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd023\sub-sd023_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd023\sub-sd023_scans.tsv entry with eeg\sub-sd023_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd023
SD023.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD024\EEG
SD024.eeg
SD024.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD024\EEG\SD024.vhdr...
Setting channel info structure...
Reading 0 ... 2366679  =      0.000 ...  2366.679 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd024
sd024
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd024/eeg/sub-sd024_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd024/eeg/sub-sd024_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd024\eeg\sub-sd024_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd024\eeg\sub-sd024_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd024\eeg\sub-sd024_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd024\eeg\sub-sd024_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd024_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd024\sub-sd024_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd024\sub-sd024_scans.tsv entry with eeg\sub-sd024_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd024
SD024.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD025\EEG
SD025.eeg
SD025.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD025\EEG\SD025.vhdr...
Setting channel info structure...
Reading 0 ... 2372779  =      0.000 ...  2372.779 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd025
sd025
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd025/eeg/sub-sd025_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd025/eeg/sub-sd025_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd025\eeg\sub-sd025_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd025\eeg\sub-sd025_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd025\eeg\sub-sd025_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd025\eeg\sub-sd025_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd025_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd025\sub-sd025_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd025\sub-sd025_scans.tsv entry with eeg\sub-sd025_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd025
SD025.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD026\EEG
SD026.eeg
SD026.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD026\EEG\SD026.vhdr...
Setting channel info structure...
Reading 0 ... 2374139  =      0.000 ...  2374.139 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd026
sd026
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd026/eeg/sub-sd026_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd026/eeg/sub-sd026_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd026\eeg\sub-sd026_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd026\eeg\sub-sd026_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd026\eeg\sub-sd026_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd026\eeg\sub-sd026_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd026_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd026\sub-sd026_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd026\sub-sd026_scans.tsv entry with eeg\sub-sd026_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd026
SD026.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD027\EEG
SD027.eeg
SD027.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD027\EEG\SD027.vhdr...
Setting channel info structure...
Reading 0 ... 2361019  =      0.000 ...  2361.019 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd027
sd027
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd027/eeg/sub-sd027_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd027/eeg/sub-sd027_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd027\eeg\sub-sd027_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd027\eeg\sub-sd027_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd027\eeg\sub-sd027_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd027\eeg\sub-sd027_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd027_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd027\sub-sd027_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd027\sub-sd027_scans.tsv entry with eeg\sub-sd027_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd027
SD027.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD028\EEG
SD028.eeg
SD028.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD028\EEG\SD028.vhdr...
Setting channel info structure...
Reading 0 ... 2362959  =      0.000 ...  2362.959 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd028
sd028
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd028/eeg/sub-sd028_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd028/eeg/sub-sd028_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd028\eeg\sub-sd028_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd028\eeg\sub-sd028_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd028\eeg\sub-sd028_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd028\eeg\sub-sd028_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd028_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd028\sub-sd028_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd028\sub-sd028_scans.tsv entry with eeg\sub-sd028_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd028
SD028.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD029\EEG
SD029.eeg
SD029.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD029\EEG\SD029.vhdr...
Setting channel info structure...
Reading 0 ... 2364679  =      0.000 ...  2364.679 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd029
sd029
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd029/eeg/sub-sd029_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd029/eeg/sub-sd029_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd029\eeg\sub-sd029_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd029\eeg\sub-sd029_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd029\eeg\sub-sd029_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd029\eeg\sub-sd029_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd029_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd029\sub-sd029_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd029\sub-sd029_scans.tsv entry with eeg\sub-sd029_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd029
SD029.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD030\EEG
SD030.eeg
SD030.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD030\EEG\SD030.vhdr...
Setting channel info structure...
Reading 0 ... 2433639  =      0.000 ...  2433.639 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd030
sd030
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd030/eeg/sub-sd030_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd030/eeg/sub-sd030_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd030\eeg\sub-sd030_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd030\eeg\sub-sd030_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd030\eeg\sub-sd030_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd030\eeg\sub-sd030_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd030_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd030\sub-sd030_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd030\sub-sd030_scans.tsv entry with eeg\sub-sd030_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd030
SD030.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD031\EEG
SD031.eeg
SD031.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD031\EEG\SD031.vhdr...
Setting channel info structure...
Reading 0 ... 2373159  =      0.000 ...  2373.159 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd031
sd031
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd031/eeg/sub-sd031_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd031/eeg/sub-sd031_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd031\eeg\sub-sd031_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd031\eeg\sub-sd031_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd031\eeg\sub-sd031_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd031\eeg\sub-sd031_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd031_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd031\sub-sd031_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd031\sub-sd031_scans.tsv entry with eeg\sub-sd031_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd031
SD031.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD032\EEG
SD032.eeg
SD032.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD032\EEG\SD032.vhdr...
Setting channel info structure...
Reading 0 ... 2430019  =      0.000 ...  2430.019 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S255']
sd032
sd032
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd032/eeg/sub-sd032_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd032/eeg/sub-sd032_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S255']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd032\eeg\sub-sd032_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd032\eeg\sub-sd032_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd032\eeg\sub-sd032_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd032\eeg\sub-sd032_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd032_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd032\sub-sd032_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd032\sub-sd032_scans.tsv entry with eeg\sub-sd032_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd032
SD032.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD033\EEG
SD033.eeg
SD033.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD033\EEG\SD033.vhdr...
Setting channel info structure...
Reading 0 ... 2366659  =      0.000 ...  2366.659 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd033
sd033
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd033/eeg/sub-sd033_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd033/eeg/sub-sd033_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd033\eeg\sub-sd033_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd033\eeg\sub-sd033_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd033\eeg\sub-sd033_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd033\eeg\sub-sd033_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd033_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd033\sub-sd033_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd033\sub-sd033_scans.tsv entry with eeg\sub-sd033_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd033
SD033.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD034\EEG
SD034.eeg
SD034.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD034\EEG\SD034.vhdr...
Setting channel info structure...
Reading 0 ... 2368819  =      0.000 ...  2368.819 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd034
sd034
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd034/eeg/sub-sd034_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd034/eeg/sub-sd034_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd034\eeg\sub-sd034_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd034\eeg\sub-sd034_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd034\eeg\sub-sd034_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd034\eeg\sub-sd034_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd034_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd034\sub-sd034_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd034\sub-sd034_scans.tsv entry with eeg\sub-sd034_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd034
SD034.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD035\EEG
SD035.eeg
SD035.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD035\EEG\SD035.vhdr...
Setting channel info structure...
Reading 0 ... 3542919  =      0.000 ...  3542.919 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
sd035
sd035
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd035/eeg/sub-sd035_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd035/eeg/sub-sd035_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd035\eeg\sub-sd035_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd035\eeg\sub-sd035_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd035\eeg\sub-sd035_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd035\eeg\sub-sd035_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd035_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd035\sub-sd035_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd035\sub-sd035_scans.tsv entry with eeg\sub-sd035_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd035
SD035.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD036\EEG
SD036.eeg
SD036.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD036\EEG\SD036.vhdr...
Setting channel info structure...
Reading 0 ... 3533879  =      0.000 ...  3533.879 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
sd036
sd036
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd036/eeg/sub-sd036_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd036/eeg/sub-sd036_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd036\eeg\sub-sd036_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd036\eeg\sub-sd036_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd036\eeg\sub-sd036_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd036\eeg\sub-sd036_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd036_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd036\sub-sd036_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd036\sub-sd036_scans.tsv entry with eeg\sub-sd036_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd036
SD036.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD037\EEG
SD037.eeg
SD037.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD037\EEG\SD037.vhdr...
Setting channel info structure...
Reading 0 ... 3530399  =      0.000 ...  3530.399 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
sd037
sd037
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd037/eeg/sub-sd037_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd037/eeg/sub-sd037_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd037\eeg\sub-sd037_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd037\eeg\sub-sd037_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd037\eeg\sub-sd037_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd037\eeg\sub-sd037_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd037_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd037\sub-sd037_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd037\sub-sd037_scans.tsv entry with eeg\sub-sd037_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd037
SD037.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD038\EEG
SD038.eeg
SD038.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD038\EEG\SD038.vhdr...
Setting channel info structure...
Reading 0 ... 3528159  =      0.000 ...  3528.159 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
sd038
sd038
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd038/eeg/sub-sd038_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd038/eeg/sub-sd038_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd038\eeg\sub-sd038_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd038\eeg\sub-sd038_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd038\eeg\sub-sd038_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd038\eeg\sub-sd038_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd038_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd038\sub-sd038_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd038\sub-sd038_scans.tsv entry with eeg\sub-sd038_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd038
SD038.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD039\EEG
SD039.eeg
SD039.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD039\EEG\SD039.vhdr...
Setting channel info structure...
Reading 0 ... 3560779  =      0.000 ...  3560.779 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
sd039
sd039
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd039/eeg/sub-sd039_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd039/eeg/sub-sd039_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd039\eeg\sub-sd039_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd039\eeg\sub-sd039_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd039\eeg\sub-sd039_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd039\eeg\sub-sd039_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd039_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd039\sub-sd039_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd039\sub-sd039_scans.tsv entry with eeg\sub-sd039_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd039
SD039.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD040\EEG
SD040.eeg
SD040.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD040\EEG\SD040.vhdr...
Setting channel info structure...
Reading 0 ... 3531839  =      0.000 ...  3531.839 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
sd040
sd040
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd040/eeg/sub-sd040_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd040/eeg/sub-sd040_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd040\eeg\sub-sd040_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd040\eeg\sub-sd040_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd040\eeg\sub-sd040_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd040\eeg\sub-sd040_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd040_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd040\sub-sd040_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd040\sub-sd040_scans.tsv entry with eeg\sub-sd040_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd040
SD040.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD041\EEG
SD041.eeg
SD041.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD041\EEG\SD041.vhdr...
Setting channel info structure...
Reading 0 ... 3638299  =      0.000 ...  3638.299 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 34', 'Stimulus/S 35']
sd041
sd041
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd041/eeg/sub-sd041_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd041/eeg/sub-sd041_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd041\eeg\sub-sd041_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd041\eeg\sub-sd041_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd041\eeg\sub-sd041_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd041\eeg\sub-sd041_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd041_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd041\sub-sd041_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd041\sub-sd041_scans.tsv entry with eeg\sub-sd041_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd041
SD041.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD042\EEG
SD042.eeg
SD042.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD042\EEG\SD042.vhdr...
Setting channel info structure...
Reading 0 ... 3543939  =      0.000 ...  3543.939 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
sd042
sd042
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd042/eeg/sub-sd042_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd042/eeg/sub-sd042_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd042\eeg\sub-sd042_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd042\eeg\sub-sd042_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd042\eeg\sub-sd042_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd042\eeg\sub-sd042_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd042_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd042\sub-sd042_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd042\sub-sd042_scans.tsv entry with eeg\sub-sd042_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd042
SD042.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD043\EEG
SD043.eeg
SD043.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD043\EEG\SD043.vhdr...
Setting channel info structure...
Reading 0 ... 3534459  =      0.000 ...  3534.459 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
sd043
sd043
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd043/eeg/sub-sd043_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd043/eeg/sub-sd043_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd043\eeg\sub-sd043_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd043\eeg\sub-sd043_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd043\eeg\sub-sd043_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd043\eeg\sub-sd043_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd043_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd043\sub-sd043_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd043\sub-sd043_scans.tsv entry with eeg\sub-sd043_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd043
SD043.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD044\EEG
SD044.eeg
SD044.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD044\EEG\SD044.vhdr...
Setting channel info structure...
Reading 0 ... 3531339  =      0.000 ...  3531.339 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
sd044
sd044
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd044/eeg/sub-sd044_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd044/eeg/sub-sd044_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd044\eeg\sub-sd044_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd044\eeg\sub-sd044_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd044\eeg\sub-sd044_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd044\eeg\sub-sd044_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd044_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd044\sub-sd044_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd044\sub-sd044_scans.tsv entry with eeg\sub-sd044_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd044
SD044.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD045\EEG
SD045.eeg
SD045.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD045\EEG\SD045.vhdr...
Setting channel info structure...
Reading 0 ... 3699119  =      0.000 ...  3699.119 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
sd045
sd045
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd045/eeg/sub-sd045_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd045/eeg/sub-sd045_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd045\eeg\sub-sd045_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd045\eeg\sub-sd045_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd045\eeg\sub-sd045_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd045\eeg\sub-sd045_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd045_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd045\sub-sd045_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd045\sub-sd045_scans.tsv entry with eeg\sub-sd045_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd045
SD045.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD046\EEG
SD046.eeg
SD046.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD046\EEG\SD046.vhdr...
Setting channel info structure...
Reading 0 ... 3703259  =      0.000 ...  3703.259 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 22', 'Stimulus/S 23', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd046
sd046
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd046/eeg/sub-sd046_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd046/eeg/sub-sd046_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 22', 'Stimulus/S 23', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd046\eeg\sub-sd046_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd046\eeg\sub-sd046_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd046\eeg\sub-sd046_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd046\eeg\sub-sd046_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd046_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd046\sub-sd046_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd046\sub-sd046_scans.tsv entry with eeg\sub-sd046_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd046
SD046.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD047\EEG
SD047.eeg
SD047.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD047\EEG\SD047.vhdr...
Setting channel info structure...
Reading 0 ... 3543399  =      0.000 ...  3543.399 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
sd047
sd047
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd047/eeg/sub-sd047_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd047/eeg/sub-sd047_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd047\eeg\sub-sd047_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd047\eeg\sub-sd047_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd047\eeg\sub-sd047_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd047\eeg\sub-sd047_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd047_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd047\sub-sd047_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd047\sub-sd047_scans.tsv entry with eeg\sub-sd047_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd047
SD047.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD048\EEG
SD048.eeg
SD048.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD048\EEG\SD048.vhdr...
Setting channel info structure...
Reading 0 ... 3558119  =      0.000 ...  3558.119 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
sd048
sd048
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd048/eeg/sub-sd048_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd048/eeg/sub-sd048_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd048\eeg\sub-sd048_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd048\eeg\sub-sd048_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd048\eeg\sub-sd048_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd048\eeg\sub-sd048_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd048_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd048\sub-sd048_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd048\sub-sd048_scans.tsv entry with eeg\sub-sd048_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd048
SD048.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD049\EEG
SD049.eeg
SD049.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD049\EEG\SD049.vhdr...
Setting channel info structure...
Reading 0 ... 3590759  =      0.000 ...  3590.759 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
sd049
sd049
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd049/eeg/sub-sd049_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd049/eeg/sub-sd049_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd049\eeg\sub-sd049_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd049\eeg\sub-sd049_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd049\eeg\sub-sd049_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd049\eeg\sub-sd049_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd049_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd049\sub-sd049_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd049\sub-sd049_scans.tsv entry with eeg\sub-sd049_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd049
SD049.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD050\EEG
SD050.eeg
SD050.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD050\EEG\SD050.vhdr...
Setting channel info structure...
Reading 0 ... 3612719  =      0.000 ...  3612.719 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd050
sd050
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd050/eeg/sub-sd050_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd050/eeg/sub-sd050_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd050\eeg\sub-sd050_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd050\eeg\sub-sd050_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd050\eeg\sub-sd050_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd050\eeg\sub-sd050_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd050_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd050\sub-sd050_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd050\sub-sd050_scans.tsv entry with eeg\sub-sd050_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd050
SD050.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD051\EEG
SD051.eeg
SD051.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD051\EEG\SD051.vhdr...
Setting channel info structure...
Reading 0 ... 3525619  =      0.000 ...  3525.619 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd051
sd051
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd051/eeg/sub-sd051_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd051/eeg/sub-sd051_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd051\eeg\sub-sd051_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd051\eeg\sub-sd051_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd051\eeg\sub-sd051_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd051\eeg\sub-sd051_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd051_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd051\sub-sd051_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd051\sub-sd051_scans.tsv entry with eeg\sub-sd051_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd051
SD051.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD052\EEG
SD052.eeg
SD052.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD052\EEG\SD052.vhdr...
Setting channel info structure...
Reading 0 ... 3547979  =      0.000 ...  3547.979 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd052
sd052
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd052/eeg/sub-sd052_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd052/eeg/sub-sd052_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd052\eeg\sub-sd052_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd052\eeg\sub-sd052_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd052\eeg\sub-sd052_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd052\eeg\sub-sd052_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd052_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd052\sub-sd052_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd052\sub-sd052_scans.tsv entry with eeg\sub-sd052_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd052
SD052.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD053\EEG
SD053.eeg
SD053.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD053\EEG\SD053.vhdr...
Setting channel info structure...
Reading 0 ... 3550199  =      0.000 ...  3550.199 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd053
sd053
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd053/eeg/sub-sd053_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd053/eeg/sub-sd053_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd053\eeg\sub-sd053_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd053\eeg\sub-sd053_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd053\eeg\sub-sd053_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd053\eeg\sub-sd053_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd053_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd053\sub-sd053_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd053\sub-sd053_scans.tsv entry with eeg\sub-sd053_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd053
SD053.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD054\EEG
SD054.eeg
SD054.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD054\EEG\SD054.vhdr...
Setting channel info structure...
Reading 0 ... 3568419  =      0.000 ...  3568.419 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd054
sd054
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd054/eeg/sub-sd054_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd054/eeg/sub-sd054_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd054\eeg\sub-sd054_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd054\eeg\sub-sd054_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd054\eeg\sub-sd054_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd054\eeg\sub-sd054_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd054_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd054\sub-sd054_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd054\sub-sd054_scans.tsv entry with eeg\sub-sd054_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd054
SD054.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD055\EEG
SD055.eeg
SD055.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD055\EEG\SD055.vhdr...
Setting channel info structure...
Reading 0 ... 3559259  =      0.000 ...  3559.259 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd055
sd055
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd055/eeg/sub-sd055_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd055/eeg/sub-sd055_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd055\eeg\sub-sd055_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd055\eeg\sub-sd055_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd055\eeg\sub-sd055_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd055\eeg\sub-sd055_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd055_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd055\sub-sd055_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd055\sub-sd055_scans.tsv entry with eeg\sub-sd055_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd055
SD055.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD056\EEG
SD056.eeg
SD056.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD056\EEG\SD056.vhdr...
Setting channel info structure...
Reading 0 ... 3551219  =      0.000 ...  3551.219 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd056
sd056
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd056/eeg/sub-sd056_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd056/eeg/sub-sd056_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd056\eeg\sub-sd056_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd056\eeg\sub-sd056_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd056\eeg\sub-sd056_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd056\eeg\sub-sd056_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd056_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd056\sub-sd056_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd056\sub-sd056_scans.tsv entry with eeg\sub-sd056_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd056
SD056.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD057\EEG
SD057.eeg
SD057.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD057\EEG\SD057.vhdr...
Setting channel info structure...
Reading 0 ... 3680739  =      0.000 ...  3680.739 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 22', 'Stimulus/S 23', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd057
sd057
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd057/eeg/sub-sd057_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd057/eeg/sub-sd057_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 12', 'Stimulus/S 13', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 22', 'Stimulus/S 23', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd057\eeg\sub-sd057_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd057\eeg\sub-sd057_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd057\eeg\sub-sd057_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd057\eeg\sub-sd057_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd057_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd057\sub-sd057_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd057\sub-sd057_scans.tsv entry with eeg\sub-sd057_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd057
SD057.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD058\EEG
SD058.eeg
SD058.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD058\EEG\SD058.vhdr...
Setting channel info structure...
Reading 0 ... 2369699  =      0.000 ...  2369.699 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd058
sd058
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd058/eeg/sub-sd058_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd058/eeg/sub-sd058_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd058\eeg\sub-sd058_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd058\eeg\sub-sd058_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd058\eeg\sub-sd058_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd058\eeg\sub-sd058_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd058_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd058\sub-sd058_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd058\sub-sd058_scans.tsv entry with eeg\sub-sd058_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd058
SD058.vmrk
SD058_B3.eeg
SD058_B3.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD058\EEG\SD058_B3.vhdr...
Setting channel info structure...
Reading 0 ... 1190499  =      0.000 ...  1190.499 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
sd058
sd058
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd058/eeg/sub-sd058_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd058/eeg/sub-sd058_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd058\eeg\sub-sd058_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd058\eeg\sub-sd058_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd058\eeg\sub-sd058_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd058\eeg\sub-sd058_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd058_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd058\sub-sd058_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd058\sub-sd058_scans.tsv entry with eeg\sub-sd058_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd058
SD058_B3.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD059\EEG
SD059.eeg
SD059.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD059\EEG\SD059.vhdr...
Setting channel info structure...
Reading 0 ... 3666059  =      0.000 ...  3666.059 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd059
sd059
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd059/eeg/sub-sd059_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd059/eeg/sub-sd059_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd059\eeg\sub-sd059_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd059\eeg\sub-sd059_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd059\eeg\sub-sd059_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd059\eeg\sub-sd059_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd059_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd059\sub-sd059_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd059\sub-sd059_scans.tsv entry with eeg\sub-sd059_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd059
SD059.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD060\EEG
SD060.eeg
SD060.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD060\EEG\SD060.vhdr...
Setting channel info structure...
Reading 0 ... 3547779  =      0.000 ...  3547.779 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd060
sd060
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd060/eeg/sub-sd060_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd060/eeg/sub-sd060_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd060\eeg\sub-sd060_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd060\eeg\sub-sd060_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd060\eeg\sub-sd060_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd060\eeg\sub-sd060_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd060_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd060\sub-sd060_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd060\sub-sd060_scans.tsv entry with eeg\sub-sd060_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd060
SD060.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD061\EEG
SD061.eeg
SD061.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD061\EEG\SD061.vhdr...
Setting channel info structure...
Reading 0 ... 3722899  =      0.000 ...  3722.899 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 22', 'Stimulus/S 23', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd061
sd061
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd061/eeg/sub-sd061_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd061/eeg/sub-sd061_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 22', 'Stimulus/S 23', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd061\eeg\sub-sd061_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd061\eeg\sub-sd061_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd061\eeg\sub-sd061_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd061\eeg\sub-sd061_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd061_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd061\sub-sd061_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd061\sub-sd061_scans.tsv entry with eeg\sub-sd061_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd061
SD061.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD062\EEG
SD062.eeg
SD062.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD062\EEG\SD062.vhdr...
Setting channel info structure...
Reading 0 ... 3546339  =      0.000 ...  3546.339 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd062
sd062
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd062/eeg/sub-sd062_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd062/eeg/sub-sd062_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd062\eeg\sub-sd062_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd062\eeg\sub-sd062_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd062\eeg\sub-sd062_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd062\eeg\sub-sd062_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd062_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd062\sub-sd062_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd062\sub-sd062_scans.tsv entry with eeg\sub-sd062_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd062
SD062.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD063\EEG
SD063.eeg
SD063.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD063\EEG\SD063.vhdr...
Setting channel info structure...
Reading 0 ... 3567379  =      0.000 ...  3567.379 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd063
sd063
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd063/eeg/sub-sd063_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd063/eeg/sub-sd063_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd063\eeg\sub-sd063_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd063\eeg\sub-sd063_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd063\eeg\sub-sd063_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd063\eeg\sub-sd063_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd063_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd063\sub-sd063_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd063\sub-sd063_scans.tsv entry with eeg\sub-sd063_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd063
SD063.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD064\EEG
SD064.eeg
SD064.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD064\EEG\SD064.vhdr...
Setting channel info structure...
Reading 0 ... 3614059  =      0.000 ...  3614.059 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd064
sd064
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd064/eeg/sub-sd064_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd064/eeg/sub-sd064_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd064\eeg\sub-sd064_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd064\eeg\sub-sd064_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd064\eeg\sub-sd064_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd064\eeg\sub-sd064_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd064_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd064\sub-sd064_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd064\sub-sd064_scans.tsv entry with eeg\sub-sd064_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd064
SD064.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD065\EEG
SD065.eeg
SD065.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD065\EEG\SD065.vhdr...
Setting channel info structure...
Reading 0 ... 3547179  =      0.000 ...  3547.179 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd065
sd065
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd065/eeg/sub-sd065_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd065/eeg/sub-sd065_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd065\eeg\sub-sd065_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd065\eeg\sub-sd065_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd065\eeg\sub-sd065_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd065\eeg\sub-sd065_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd065_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd065\sub-sd065_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd065\sub-sd065_scans.tsv entry with eeg\sub-sd065_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd065
SD065.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD066\EEG
SD066.eeg
SD066.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD066\EEG\SD066.vhdr...
Setting channel info structure...
Reading 0 ... 3539699  =      0.000 ...  3539.699 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd066
sd066
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd066/eeg/sub-sd066_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd066/eeg/sub-sd066_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd066\eeg\sub-sd066_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd066\eeg\sub-sd066_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd066\eeg\sub-sd066_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd066\eeg\sub-sd066_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd066_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd066\sub-sd066_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd066\sub-sd066_scans.tsv entry with eeg\sub-sd066_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd066
SD066.vmrk
D:\Work_data\Notification_evoked_response\Data_at_IITD/SD067\EEG
SD067.eeg
SD067.vhdr
Extracting parameters from D:\Work_data\Notification_evoked_response\Data_at_IITD/SD067\EEG\SD067.vhdr...
Setting channel info structure...
Reading 0 ... 3541379  =      0.000 ...  3541.379 secs...
Location for this channel is unknown; consider calling set_montage() after adding new reference channels if needed. Applying a montage will only set locations of channels that exist at the time it is applied.
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
sd067
sd067
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\participants.json'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd067/eeg/sub-sd067_space-CapTrak_electrodes.tsv'...
Writing 'D:/Work_data/Notification_evoked_response/Data_at_IITD/bids_data/sub-sd067/eeg/sub-sd067_space-CapTrak_coordsystem.json'...
Used Annotations descriptions: ['Comment/Active Shielding: On', 'New Segment/', 'Stimulus/S 11', 'Stimulus/S 14', 'Stimulus/S 15', 'Stimulus/S 21', 'Stimulus/S 24', 'Stimulus/S 25', 'Stimulus/S 31', 'Stimulus/S 32', 'Stimulus/S 33', 'Stimulus/S 34', 'Stimulus/S 35']
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd067\eeg\sub-sd067_task-auditoryoddball_events.tsv'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd067\eeg\sub-sd067_task-auditoryoddball_events.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\dataset_description.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd067\eeg\sub-sd067_task-auditoryoddball_eeg.json'...
Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd067\eeg\sub-sd067_task-auditoryoddball_channels.tsv'...
Copying data files to sub-sd067_task-auditoryoddball_eeg.vhdr

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\2585926677.py:40: RuntimeWarning: Converting data files to BrainVision format
  write_raw_bids(raw, bids_path=bids_path,events=events,event_id= event_dict, overwrite=True,allow_preload=True, format='BrainVision')
c:\Users\PRAKASH\AppData\Local\anaconda3\envs\EEG_analysis\Lib\site-packages\pybv\io.py:682: UserWarning: Encountered unsupported non-voltage units: C
Note that the BrainVision format specification supports only µV.
  warn(msg)

Writing 'D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd067\sub-sd067_scans.tsv'...
Wrote D:\Work_data\Notification_evoked_response\Data_at_IITD\bids_data\sub-sd067\sub-sd067_scans.tsv entry with eeg\sub-sd067_task-auditoryoddball_eeg.vhdr.
Converted D:\Work_data\Notification_evoked_response\Data_at_IITD/ → sub-sd067
SD067.vmrk

### Create Participants file

In [2]:
import json
import os

# Define the metadata dictionary
participants_metadata = {
    "participant_id": {
        "Description": "BIDS participant identifier"
    },
    "age": {
        "Description": "Age of the participant in years"
    },
    "is_controlled_block": {
        "Description": "Whether the participant was in a controlled tone block (yes or no)"
    },
    "gender": {
        "Description": "Biological sex of the participant, M or F"
    },
    "profession": {
        "Description": "Participant's profession"
    },
    "b1_deviant": {
        "Description": "Block1 deviant auditory tone",
        "Levels": {
            "PN": "Personal notification",
            "BT": "Beep tone",
            "CN": "Control notification"
        }
    },
    "b2_deviant": {
        "Description": "Block2 deviant auditory tone",
        "Levels": {
            "PN": "Personal notification",
            "BT": "Beep tone",
            "CN": "Control notification"
        }
    },
    "b3_deviant": {
        "Description": "Block3 deviant auditory tone",
        "Levels": {
            "PN": "Personal notification",
            "BT": "Beep tone",
            "CN": "Control notification"
        }
    }
}

# Create BIDS dataset directory if it doesn't exist
os.makedirs(r'D:\Work_data\Notification_evoked_response\Data_at_IITD/bids_data', exist_ok=True)

# Save the dictionary as a JSON file
with open(r'D:\Work_data\Notification_evoked_response\Data_at_IITD/bids_data/participants.json', 'w') as json_file:
    json.dump(participants_metadata, json_file, indent=4)

In [1]:
import pandas as pd
import os

# Load the Excel file
df = pd.read_excel('E:\ecf-exp2-notif-mmn\data\Processed\Participant_details.xlsx')
# Save as participants.tsv (tab-separated)
df['participant_id'] = ['sub-' + val.lower() for val in df['participant_id'] ] 
df.to_csv(r'D:\Work_data\Notification_evoked_response\Data_at_IITD/bids_data/participants.tsv', sep='\t', index=False)
df.head()

<>:5: SyntaxWarning: invalid escape sequence '\e'
<>:5: SyntaxWarning: invalid escape sequence '\e'
C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_14128\2221517279.py:5: SyntaxWarning: invalid escape sequence '\e'
  df = pd.read_excel('E:\ecf-exp2-notif-mmn\data\Processed\Participant_details.xlsx')

,participant_id,age,is_controlled_block,gender,profession,b1_deviant,b2_deviant,b3_deviant
0,sub-sd011,30,N,M,PG_acd,PN,BT,NaN
1,sub-sd012,25,N,M,PG_acd,PN,BT,NaN
2,sub-sd013,25,N,M,PG_acd,PN,BT,NaN
3,sub-sd014,28,N,M,PG_acd,PN,BT,NaN
4,sub-sd015,31,N,M,PG_acd,PN,BT,NaN

### Surevy response

In [53]:
sub_df  = pd.read_excel('E:\ecf-exp2-notif-mmn\data\Processed\ECF Participant Data.xlsx')
sub_df.head()

<>:1: SyntaxWarning: invalid escape sequence '\e'
<>:1: SyntaxWarning: invalid escape sequence '\e'
C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\1136174520.py:1: SyntaxWarning: invalid escape sequence '\e'
  sub_df  = pd.read_excel('E:\ecf-exp2-notif-mmn\data\Processed\ECF Participant Data.xlsx')

,Timestamp,Email Address,Subject ID,I can never spend enough time on my mobile phone.,I have used my mobile phone to make myself feel better when I was feeling down.,"I find myself occupied on my mobile phone when I should be doing other things, and it causes problems.",All my friends own a mobile phone.,I have tried to hide from others how much time I spend on my mobile phone.,I lose sleep due to the time I spend on my mobile phone.,I have received mobile phone bills I could not afford to pay.,...,How much do you agree with the statement: I am addicted to my smartphone?,My phone is on [Silent / DND],My phone is on [Vibrate only],My phone is on [Loud],Do you receive notifications on some other device instead (like a smartwatch)?,What emotions are typically associated with receiving smartphone notifications?,How did you feel about the notifications during the first half of the experiment?,How did you feel about the notifications during the 2nd half of the experiment?,MPPUS,SAS
0,2024-05-15 11:36:03.174,sgandhi@iitj.ac.in,sub002,3,7,2,10,2,2,1,...,Disagree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60,50
1,2024-05-27 17:36:20.547,tanvi.gandhi.ajmer@gmail.com,sub003,8,9,9,10,9,9,5,...,Strongly agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176,130
2,2024-05-28 13:42:27.613,rishabh1000khandelwal@gmail.com,sub004,5,10,7,10,1,6,1,...,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,124,107
3,2024-05-29 19:50:37.592,m23air013@iitj.ac.in,sub005,2,10,7,10,4,9,1,...,Disagree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,140,104
4,2024-05-31 18:33:04.260,anikde@iitj.ac.in,sub006,8,7,7,10,4,8,1,...,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107,60

In [54]:
exp0_df = pd.read_excel('E:\ecf-exp2-notif-mmn\data\Processed\ECF Exp 0.xlsx')
exp0_df.head()

<>:1: SyntaxWarning: invalid escape sequence '\e'
<>:1: SyntaxWarning: invalid escape sequence '\e'
C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\3099290216.py:1: SyntaxWarning: invalid escape sequence '\e'
  exp0_df = pd.read_excel('E:\ecf-exp2-notif-mmn\data\Processed\ECF Exp 0.xlsx')

,Timestamp,Email Address,Name,Age,Gender,Occupation,Education,Phone number,I can never spend enough time on my mobile phone.,I have used my mobile phone to make myself feel better when I was feeling down.,...,Always thinking that I should shorten my smartphone use time.,The people around me tell me that I use my smartphone too much.,How much do you agree with the statement: I am addicted to my smartphone?,My phone is on [Silent / DND],My phone is on [Vibrate only],My phone is on [Loud],Do you receive notifications on some other device instead (like a smartwatch)?,What emotions do you typically associate with receiving smartphone notifications?,MPPUS Score,SAS Score
0,2024-10-29 16:22:59.751,sgandhi@iitj.ac.in,Saurabh Gandhi,33,Male,Teacher,Post graduate,8446487634,2,8,...,1,1,Disagree,Often,Always,Sometimes,No,Exciting,63.0,54.0
1,2024-10-30 18:38:17.875,p24ai0003@iitj.ac.in,Pragya Verma,26,Female,Student,Post graduate,7843862035,2,9,...,2,1,Strongly disagree,Never,Always,Never,No,Exciting,128.0,84.0
2,2024-11-02 12:15:41.405,m23irm009@iitj.ac.in,NISHANT PRATAP SINGH,24,Male,STUDENT,Post graduate,7017919704,4,4,...,3,2,Disagree,Sometimes,Sometimes,Often,No,Exciting,147.0,79.0
3,2024-11-02 20:00:03.825,m23irm001@iitj.ac.in,Aditya Bhargava,24,Male,Student,Post graduate,9672987879,1,2,...,1,1,Strongly disagree,Sometimes,Sometimes,Sometimes,No,Neutral,51.0,47.0
4,2024-11-07 21:45:25.883,m23irm012@iitj.ac.in,Swapnil Singh,26,Male,Student,Post graduate,7904318618,4,8,...,2,1,Agree,Often,Always,Often,Yes,Exciting,153.0,104.0

In [55]:


# Function to create participant ID
def make_participant_id(row):

    name_part = str(row['Name'])[:2].lower()
    
    gender_part = str(row['Gender'])[0].lower()
    num_part = str(row['Phone number'])[:2].lower()
    education_part = str(row['Education'])[:2].lower()
    return f"{name_part}{gender_part}{education_part}{num_part}"

# Apply the function to create a new column
exp0_df['Subject ID'] = exp0_df.apply(make_participant_id, axis=1)

exp0_df.head()

,Timestamp,Email Address,Name,Age,Gender,Occupation,Education,Phone number,I can never spend enough time on my mobile phone.,I have used my mobile phone to make myself feel better when I was feeling down.,...,The people around me tell me that I use my smartphone too much.,How much do you agree with the statement: I am addicted to my smartphone?,My phone is on [Silent / DND],My phone is on [Vibrate only],My phone is on [Loud],Do you receive notifications on some other device instead (like a smartwatch)?,What emotions do you typically associate with receiving smartphone notifications?,MPPUS Score,SAS Score,Subject ID
0,2024-10-29 16:22:59.751,sgandhi@iitj.ac.in,Saurabh Gandhi,33,Male,Teacher,Post graduate,8446487634,2,8,...,1,Disagree,Often,Always,Sometimes,No,Exciting,63.0,54.0,sampo84
1,2024-10-30 18:38:17.875,p24ai0003@iitj.ac.in,Pragya Verma,26,Female,Student,Post graduate,7843862035,2,9,...,1,Strongly disagree,Never,Always,Never,No,Exciting,128.0,84.0,prfpo78
2,2024-11-02 12:15:41.405,m23irm009@iitj.ac.in,NISHANT PRATAP SINGH,24,Male,STUDENT,Post graduate,7017919704,4,4,...,2,Disagree,Sometimes,Sometimes,Often,No,Exciting,147.0,79.0,nimpo70
3,2024-11-02 20:00:03.825,m23irm001@iitj.ac.in,Aditya Bhargava,24,Male,Student,Post graduate,9672987879,1,2,...,1,Strongly disagree,Sometimes,Sometimes,Sometimes,No,Neutral,51.0,47.0,admpo96
4,2024-11-07 21:45:25.883,m23irm012@iitj.ac.in,Swapnil Singh,26,Male,Student,Post graduate,7904318618,4,8,...,1,Agree,Often,Always,Often,Yes,Exciting,153.0,104.0,swmpo79

In [56]:

print("Common columns:", list(exp0_df.columns.intersection(sub_df.columns)))
print("Columns only in exp0_df:", list(exp0_df.columns.difference(sub_df.columns)))
print("Columns only in sub_df:", list(sub_df.columns.difference(exp0_df.columns)))

Common columns: ['Timestamp', 'Email Address', 'I can never spend enough time on my mobile phone.', 'I have used my mobile phone to make myself feel better when I was feeling down.', 'I find myself occupied on my mobile phone when I should be doing other things, and it causes problems.', 'All my friends own a mobile phone.', 'I have tried to hide from others how much time I spend on my mobile phone.', 'I lose sleep due to the time I spend on my mobile phone.', 'I have received mobile phone bills I could not afford to pay.', 'When out of range for some time, I become preoccupied with the thought of missing a call.', 'Sometimes, when I am on the mobile phone and I am doing other things, I get carried away with the conversation and I don’t pay attention to what I am doing.', 'The time I spend on the mobile phone has increased over the last 12 months.', 'I have used my mobile phone to talk to others when I was feeling isolated.', 'I have attempted to spend less time on my mobile phone but am unable to.', 'I find it difficult to switch off my mobile phone.', 'I feel anxious if I have not checked for messages or switched on my mobile phone for some time.', 'I have frequent dreams about the mobile phone.', 'My friends and family complain about my use of the mobile phone.', "If I don't have a mobile phone, my friends would find it hard to get in touch with me. ", 'My productivity has decreased as a direct result of the time I spend on the mobile phone.', 'I have aches and pains that are associated with my mobile phone use.', 'I find myself engaged on the mobile phone for longer periods of time than intended.', 'There are times when I would rather use the mobile phone than deal with other more pressing issues.', "I am often late for appointments because I'm engaged on the mobile phone when I shouldn't be.", 'I become irritable if I have to switch off my mobile phone for meetings, dinner engagements, or at the movies.', 'I have been told that I spend too much time on my mobile phone.', 'More than once I have been in trouble because my mobile phone has gone off during a meeting, lecture, or in a theatre.', "My friends don't like it when my mobile phone is switched off.", 'I feel lost without my mobile phone.', 'Missing planned work due to smartphone use.', 'Having a hard time concentrating in class, while doing assignments, or while working due to smartphone use.', 'Experiencing lightheadedness or blurred vision due to excessive smartphone use.', 'Feeling pain in the wrists or at the back of the neck while using a smartphone.', 'Feeling tired and lacking adequate sleep due to excessive smartphone use.', 'Feeling calm or cozy while using a smartphone.', 'Feeling pleasant or excited while using a smartphone.', 'Feeling confident while using a smartphone.', 'Being able to get rid of stress with a smartphone.', 'There is nothing more fun to do than using my smartphone.', 'My life would be empty without my smartphone. ', 'Feeling most liberal while using a smartphone.', 'Using a smartphone is the most fun thing to do. ', 'Won’t be able to stand not having a smartphone.', 'Feeling impatient and fretful when I am not holding my smartphone.', 'Having my smartphone in my mind even when I am not using it.', 'Getting irritated when bothered while using my smartphone.', 'Bringing my smartphone to the toilet even when I am in a hurry to get there.', 'Feeling great meeting more people via smartphone use.', 'Feeling that my relationships with my smartphone buddies are more intimate than my\nrelationships with my real-life friends.', 'Not being able to use my smartphone would be as painful as losing a friend.', 'Feeling that my smartphone buddies understand me better than my real-life friends.', 'Preferring talking with my smartphone buddies to hanging out with my real-life friends or\nwith the other members of my family.', 'Preferring searching from my smartphone to asking other people.', 'My fully charged battery does not last for one whole day.', 'Using my smartphone longer than I had intended.', 'Feeling the urge to use my smartphone again right after I stopped using it.', 'Having tried time and again to shorten my smartphone use time, but failing all the time.', 'Always thinking that I should shorten my smartphone use time.', 'The people around me tell me that I use my smartphone too much.', 'How much do you agree with the statement: I am addicted to my smartphone?', 'My phone is on [Silent / DND]', 'My phone is on [Vibrate only]', 'My phone is on [Loud]', 'Do you receive notifications on some other device instead (like a smartwatch)?', 'Subject ID']
Columns only in exp0_df: ['Age', 'Checking Messaging and Social Networking apps right after waking up. ', 'Constantly checking my smartphone so as not to miss conversations between other people on Social Media.', 'Education', 'Gender', 'I will never give up using my smartphone even when my \ndaily life is already greatly affected by it.', 'MPPUS Score', 'Name', 'Occupation', 'Phone number', 'SAS Score', 'What emotions do you typically associate with receiving smartphone notifications?']
Columns only in sub_df: ['Checking SNS (Social Networking Service) sites like Twitter or Facebook right after waking up.', 'Constantly checking my smartphone so as not to miss conversations between other people\non Twitter or Facebook.', 'How did you feel about the notifications during the 2nd half of the experiment?', 'How did you feel about the notifications during the first half of the experiment?', 'I will never give up using my smartphone even when my daily life is already greatly affected\nby it.', 'MPPUS', 'SAS', 'What emotions are typically associated with receiving smartphone notifications?']

In [57]:
exp0_df = exp0_df.rename(columns={
    'Checking Messaging and Social Networking apps right after waking up. ': 'Checking SNS (Social Networking Service) sites like Twitter or Facebook right after waking up.',
    'Constantly checking my smartphone so as not to miss conversations between other people on Social Media.': 'Constantly checking my smartphone so as not to miss conversations between other people\non Twitter or Facebook.',
    'I will never give up using my smartphone even when my \ndaily life is already greatly affected by it.': 'I will never give up using my smartphone even when my daily life is already greatly affected\nby it.',
    'SAS Score': 'SAS',
    'MPPUS Score':'MPPUS',
    'What emotions do you typically associate with receiving smartphone notifications?': 'What emotions are typically associated with receiving smartphone notifications?',
})

In [58]:

print("Common columns:", list(exp0_df.columns.intersection(sub_df.columns)))
print("Columns only in exp0_df:", list(exp0_df.columns.difference(sub_df.columns)))
print("Columns only in sub_df:", list(sub_df.columns.difference(exp0_df.columns)))

Common columns: ['Timestamp', 'Email Address', 'I can never spend enough time on my mobile phone.', 'I have used my mobile phone to make myself feel better when I was feeling down.', 'I find myself occupied on my mobile phone when I should be doing other things, and it causes problems.', 'All my friends own a mobile phone.', 'I have tried to hide from others how much time I spend on my mobile phone.', 'I lose sleep due to the time I spend on my mobile phone.', 'I have received mobile phone bills I could not afford to pay.', 'When out of range for some time, I become preoccupied with the thought of missing a call.', 'Sometimes, when I am on the mobile phone and I am doing other things, I get carried away with the conversation and I don’t pay attention to what I am doing.', 'The time I spend on the mobile phone has increased over the last 12 months.', 'I have used my mobile phone to talk to others when I was feeling isolated.', 'I have attempted to spend less time on my mobile phone but am unable to.', 'I find it difficult to switch off my mobile phone.', 'I feel anxious if I have not checked for messages or switched on my mobile phone for some time.', 'I have frequent dreams about the mobile phone.', 'My friends and family complain about my use of the mobile phone.', "If I don't have a mobile phone, my friends would find it hard to get in touch with me. ", 'My productivity has decreased as a direct result of the time I spend on the mobile phone.', 'I have aches and pains that are associated with my mobile phone use.', 'I find myself engaged on the mobile phone for longer periods of time than intended.', 'There are times when I would rather use the mobile phone than deal with other more pressing issues.', "I am often late for appointments because I'm engaged on the mobile phone when I shouldn't be.", 'I become irritable if I have to switch off my mobile phone for meetings, dinner engagements, or at the movies.', 'I have been told that I spend too much time on my mobile phone.', 'More than once I have been in trouble because my mobile phone has gone off during a meeting, lecture, or in a theatre.', "My friends don't like it when my mobile phone is switched off.", 'I feel lost without my mobile phone.', 'Missing planned work due to smartphone use.', 'Having a hard time concentrating in class, while doing assignments, or while working due to smartphone use.', 'Experiencing lightheadedness or blurred vision due to excessive smartphone use.', 'Feeling pain in the wrists or at the back of the neck while using a smartphone.', 'Feeling tired and lacking adequate sleep due to excessive smartphone use.', 'Feeling calm or cozy while using a smartphone.', 'Feeling pleasant or excited while using a smartphone.', 'Feeling confident while using a smartphone.', 'Being able to get rid of stress with a smartphone.', 'There is nothing more fun to do than using my smartphone.', 'My life would be empty without my smartphone. ', 'Feeling most liberal while using a smartphone.', 'Using a smartphone is the most fun thing to do. ', 'Won’t be able to stand not having a smartphone.', 'Feeling impatient and fretful when I am not holding my smartphone.', 'Having my smartphone in my mind even when I am not using it.', 'I will never give up using my smartphone even when my daily life is already greatly affected\nby it.', 'Getting irritated when bothered while using my smartphone.', 'Bringing my smartphone to the toilet even when I am in a hurry to get there.', 'Feeling great meeting more people via smartphone use.', 'Feeling that my relationships with my smartphone buddies are more intimate than my\nrelationships with my real-life friends.', 'Not being able to use my smartphone would be as painful as losing a friend.', 'Feeling that my smartphone buddies understand me better than my real-life friends.', 'Constantly checking my smartphone so as not to miss conversations between other people\non Twitter or Facebook.', 'Checking SNS (Social Networking Service) sites like Twitter or Facebook right after waking up.', 'Preferring talking with my smartphone buddies to hanging out with my real-life friends or\nwith the other members of my family.', 'Preferring searching from my smartphone to asking other people.', 'My fully charged battery does not last for one whole day.', 'Using my smartphone longer than I had intended.', 'Feeling the urge to use my smartphone again right after I stopped using it.', 'Having tried time and again to shorten my smartphone use time, but failing all the time.', 'Always thinking that I should shorten my smartphone use time.', 'The people around me tell me that I use my smartphone too much.', 'How much do you agree with the statement: I am addicted to my smartphone?', 'My phone is on [Silent / DND]', 'My phone is on [Vibrate only]', 'My phone is on [Loud]', 'Do you receive notifications on some other device instead (like a smartwatch)?', 'What emotions are typically associated with receiving smartphone notifications?', 'MPPUS', 'SAS', 'Subject ID']
Columns only in exp0_df: ['Age', 'Education', 'Gender', 'Name', 'Occupation', 'Phone number']
Columns only in sub_df: ['How did you feel about the notifications during the 2nd half of the experiment?', 'How did you feel about the notifications during the first half of the experiment?']

In [ ]:

combined_df = pd.concat([sub_df, exp0_df], ignore_index=True)
combined_df  = combined_df.rename(columns={
    'Subject ID': 'participant_id',  
})
combined_df.head(100)

In [78]:
combined_df = combined_df.drop(columns=['Age', 'Education', 'Gender', 'Name', 'Occupation', 'Phone number','Email Address','Timestamp'])
combined_df.to_csv("data.csv")
combined_df.head()

,participant_id,I can never spend enough time on my mobile phone.,I have used my mobile phone to make myself feel better when I was feeling down.,"I find myself occupied on my mobile phone when I should be doing other things, and it causes problems.",All my friends own a mobile phone.,I have tried to hide from others how much time I spend on my mobile phone.,I lose sleep due to the time I spend on my mobile phone.,I have received mobile phone bills I could not afford to pay.,"When out of range for some time, I become preoccupied with the thought of missing a call.","Sometimes, when I am on the mobile phone and I am doing other things, I get carried away with the conversation and I don’t pay attention to what I am doing.",...,How much do you agree with the statement: I am addicted to my smartphone?,My phone is on [Silent / DND],My phone is on [Vibrate only],My phone is on [Loud],Do you receive notifications on some other device instead (like a smartwatch)?,What emotions are typically associated with receiving smartphone notifications?,How did you feel about the notifications during the first half of the experiment?,How did you feel about the notifications during the 2nd half of the experiment?,MPPUS,SAS
0,sub002,3,7,2,10,2,2,1,1,2,...,Disagree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,50.0
1,sub003,8,9,9,10,9,9,5,4,6,...,Strongly agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176.0,130.0
2,sub004,5,10,7,10,1,6,1,1,3,...,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,124.0,107.0
3,sub005,2,10,7,10,4,9,1,2,4,...,Disagree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,140.0,104.0
4,sub006,8,7,7,10,4,8,1,4,3,...,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.0,60.0

In [114]:
mppus_response  = combined_df.iloc[:, :28]
mppus_response.head()

,participant_id,I can never spend enough time on my mobile phone.,I have used my mobile phone to make myself feel better when I was feeling down.,"I find myself occupied on my mobile phone when I should be doing other things, and it causes problems.",All my friends own a mobile phone.,I have tried to hide from others how much time I spend on my mobile phone.,I lose sleep due to the time I spend on my mobile phone.,I have received mobile phone bills I could not afford to pay.,"When out of range for some time, I become preoccupied with the thought of missing a call.","Sometimes, when I am on the mobile phone and I am doing other things, I get carried away with the conversation and I don’t pay attention to what I am doing.",...,My productivity has decreased as a direct result of the time I spend on the mobile phone.,I have aches and pains that are associated with my mobile phone use.,I find myself engaged on the mobile phone for longer periods of time than intended.,There are times when I would rather use the mobile phone than deal with other more pressing issues.,I am often late for appointments because I'm engaged on the mobile phone when I shouldn't be.,"I become irritable if I have to switch off my mobile phone for meetings, dinner engagements, or at the movies.",I have been told that I spend too much time on my mobile phone.,"More than once I have been in trouble because my mobile phone has gone off during a meeting, lecture, or in a theatre.",My friends don't like it when my mobile phone is switched off.,I feel lost without my mobile phone.
0,sub002,3,7,2,10,2,2,1,1,2,...,2,1,2,1,1,1,2,2,2,1
1,sub003,8,9,9,10,9,9,5,4,6,...,9,5,9,10,5,4,7,4,3,7
2,sub004,5,10,7,10,1,6,1,1,3,...,2,2,6,7,1,3,7,1,1,10
3,sub005,2,10,7,10,4,9,1,2,4,...,7,3,7,8,3,2,3,8,7,4
4,sub006,8,7,7,10,4,8,1,4,3,...,4,1,7,1,1,1,2,1,4,2

In [ ]:
mppus_response.columns

In [116]:

mppus_response_dict = {'participant_id' : "BIDS participant identifier"}
for i ,qus in enumerate(mppus_response.columns):
    if i >0 : 
        qus_num = "Q"+str(i)
        mppus_response_dict[qus_num]= qus
mppus_response_dict

{'participant_id': 'BIDS participant identifier',
 'Q1': 'I can never spend enough time on my mobile phone.',
 'Q2': 'I have used my mobile phone to make myself feel better when I was feeling down.',
 'Q3': 'I find myself occupied on my mobile phone when I should be doing other things, and it causes problems.',
 'Q4': 'All my friends own a mobile phone.',
 'Q5': 'I have tried to hide from others how much time I spend on my mobile phone.',
 'Q6': 'I lose sleep due to the time I spend on my mobile phone.',
 'Q7': 'I have received mobile phone bills I could not afford to pay.',
 'Q8': 'When out of range for some time, I become preoccupied with the thought of missing a call.',
 'Q9': 'Sometimes, when I am on the mobile phone and I am doing other things, I get carried away with the conversation and I don’t pay attention to what I am doing.',
 'Q10': 'The time I spend on the mobile phone has increased over the last 12 months.',
 'Q11': 'I have used my mobile phone to talk to others when I was feeling isolated.',
 'Q12': 'I have attempted to spend less time on my mobile phone but am unable to.',
 'Q13': 'I find it difficult to switch off my mobile phone.',
 'Q14': 'I feel anxious if I have not checked for messages or switched on my mobile phone for some time.',
 'Q15': 'I have frequent dreams about the mobile phone.',
 'Q16': 'My friends and family complain about my use of the mobile phone.',
 'Q17': "If I don't have a mobile phone, my friends would find it hard to get in touch with me. ",
 'Q18': 'My productivity has decreased as a direct result of the time I spend on the mobile phone.',
 'Q19': 'I have aches and pains that are associated with my mobile phone use.',
 'Q20': 'I find myself engaged on the mobile phone for longer periods of time than intended.',
 'Q21': 'There are times when I would rather use the mobile phone than deal with other more pressing issues.',
 'Q22': "I am often late for appointments because I'm engaged on the mobile phone when I shouldn't be.",
 'Q23': 'I become irritable if I have to switch off my mobile phone for meetings, dinner engagements, or at the movies.',
 'Q24': 'I have been told that I spend too much time on my mobile phone.',
 'Q25': 'More than once I have been in trouble because my mobile phone has gone off during a meeting, lecture, or in a theatre.',
 'Q26': "My friends don't like it when my mobile phone is switched off.",
 'Q27': 'I feel lost without my mobile phone.'}

In [117]:

list_slice = list(mppus_response_dict.items())[1:]
sliced_dict = dict(list(mppus_response_dict.items())[1:])
print(sliced_dict)

{'Q1': 'I can never spend enough time on my mobile phone.', 'Q2': 'I have used my mobile phone to make myself feel better when I was feeling down.', 'Q3': 'I find myself occupied on my mobile phone when I should be doing other things, and it causes problems.', 'Q4': 'All my friends own a mobile phone.', 'Q5': 'I have tried to hide from others how much time I spend on my mobile phone.', 'Q6': 'I lose sleep due to the time I spend on my mobile phone.', 'Q7': 'I have received mobile phone bills I could not afford to pay.', 'Q8': 'When out of range for some time, I become preoccupied with the thought of missing a call.', 'Q9': 'Sometimes, when I am on the mobile phone and I am doing other things, I get carried away with the conversation and I don’t pay attention to what I am doing.', 'Q10': 'The time I spend on the mobile phone has increased over the last 12 months.', 'Q11': 'I have used my mobile phone to talk to others when I was feeling isolated.', 'Q12': 'I have attempted to spend less time on my mobile phone but am unable to.', 'Q13': 'I find it difficult to switch off my mobile phone.', 'Q14': 'I feel anxious if I have not checked for messages or switched on my mobile phone for some time.', 'Q15': 'I have frequent dreams about the mobile phone.', 'Q16': 'My friends and family complain about my use of the mobile phone.', 'Q17': "If I don't have a mobile phone, my friends would find it hard to get in touch with me. ", 'Q18': 'My productivity has decreased as a direct result of the time I spend on the mobile phone.', 'Q19': 'I have aches and pains that are associated with my mobile phone use.', 'Q20': 'I find myself engaged on the mobile phone for longer periods of time than intended.', 'Q21': 'There are times when I would rather use the mobile phone than deal with other more pressing issues.', 'Q22': "I am often late for appointments because I'm engaged on the mobile phone when I shouldn't be.", 'Q23': 'I become irritable if I have to switch off my mobile phone for meetings, dinner engagements, or at the movies.', 'Q24': 'I have been told that I spend too much time on my mobile phone.', 'Q25': 'More than once I have been in trouble because my mobile phone has gone off during a meeting, lecture, or in a theatre.', 'Q26': "My friends don't like it when my mobile phone is switched off.", 'Q27': 'I feel lost without my mobile phone.'}

In [129]:

# Swap keys and values
swapped_dict = {v: k for k, v in dict(list(mppus_response_dict.items())[1:]).items()}

# Display the swapped dictionary
print(swapped_dict)

{'I can never spend enough time on my mobile phone.': 'Q1', 'I have used my mobile phone to make myself feel better when I was feeling down.': 'Q2', 'I find myself occupied on my mobile phone when I should be doing other things, and it causes problems.': 'Q3', 'All my friends own a mobile phone.': 'Q4', 'I have tried to hide from others how much time I spend on my mobile phone.': 'Q5', 'I lose sleep due to the time I spend on my mobile phone.': 'Q6', 'I have received mobile phone bills I could not afford to pay.': 'Q7', 'When out of range for some time, I become preoccupied with the thought of missing a call.': 'Q8', 'Sometimes, when I am on the mobile phone and I am doing other things, I get carried away with the conversation and I don’t pay attention to what I am doing.': 'Q9', 'The time I spend on the mobile phone has increased over the last 12 months.': 'Q10', 'I have used my mobile phone to talk to others when I was feeling isolated.': 'Q11', 'I have attempted to spend less time on my mobile phone but am unable to.': 'Q12', 'I find it difficult to switch off my mobile phone.': 'Q13', 'I feel anxious if I have not checked for messages or switched on my mobile phone for some time.': 'Q14', 'I have frequent dreams about the mobile phone.': 'Q15', 'My friends and family complain about my use of the mobile phone.': 'Q16', "If I don't have a mobile phone, my friends would find it hard to get in touch with me. ": 'Q17', 'My productivity has decreased as a direct result of the time I spend on the mobile phone.': 'Q18', 'I have aches and pains that are associated with my mobile phone use.': 'Q19', 'I find myself engaged on the mobile phone for longer periods of time than intended.': 'Q20', 'There are times when I would rather use the mobile phone than deal with other more pressing issues.': 'Q21', "I am often late for appointments because I'm engaged on the mobile phone when I shouldn't be.": 'Q22', 'I become irritable if I have to switch off my mobile phone for meetings, dinner engagements, or at the movies.': 'Q23', 'I have been told that I spend too much time on my mobile phone.': 'Q24', 'More than once I have been in trouble because my mobile phone has gone off during a meeting, lecture, or in a theatre.': 'Q25', "My friends don't like it when my mobile phone is switched off.": 'Q26', 'I feel lost without my mobile phone.': 'Q27'}

In [130]:

mppus_response.rename(columns=swapped_dict,inplace=True)
mppus_response.head()

,participant_id,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,...,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27
0,sub002,3,7,2,10,2,2,1,1,2,...,2,1,2,1,1,1,2,2,2,1
1,sub003,8,9,9,10,9,9,5,4,6,...,9,5,9,10,5,4,7,4,3,7
2,sub004,5,10,7,10,1,6,1,1,3,...,2,2,6,7,1,3,7,1,1,10
3,sub005,2,10,7,10,4,9,1,2,4,...,7,3,7,8,3,2,3,8,7,4
4,sub006,8,7,7,10,4,8,1,4,3,...,4,1,7,1,1,1,2,1,4,2

In [131]:
# Create BIDS dataset directory if it doesn't exist
os.makedirs(r'D:\Work_data\Notification_evoked_response\Data_at_IITD/bids_data/phenotype/', exist_ok=True)
#  save it as a TSV file (tab-separated)
mppus_response.to_csv(r'D:\Work_data\Notification_evoked_response\Data_at_IITD/bids_data/phenotype/mppus_responses.tsv', sep='\t', index=False)
# Save the dictionary as a JSON file
with open(r'D:\Work_data\Notification_evoked_response\Data_at_IITD/bids_data/phenotype/mppus_responses.json', 'w') as json_file:
    json.dump(mppus_response_dict, json_file, indent=4)

In [136]:
sas_response  = combined_df.iloc[:, [0] + list(range(28, 61))]
sas_response.head()

,participant_id,Missing planned work due to smartphone use.,"Having a hard time concentrating in class, while doing assignments, or while working due to smartphone use.",Experiencing lightheadedness or blurred vision due to excessive smartphone use.,Feeling pain in the wrists or at the back of the neck while using a smartphone.,Feeling tired and lacking adequate sleep due to excessive smartphone use.,Feeling calm or cozy while using a smartphone.,Feeling pleasant or excited while using a smartphone.,Feeling confident while using a smartphone.,Being able to get rid of stress with a smartphone.,...,Constantly checking my smartphone so as not to miss conversations between other people\non Twitter or Facebook.,Checking SNS (Social Networking Service) sites like Twitter or Facebook right after waking up.,Preferring talking with my smartphone buddies to hanging out with my real-life friends or\nwith the other members of my family.,Preferring searching from my smartphone to asking other people.,My fully charged battery does not last for one whole day.,Using my smartphone longer than I had intended.,Feeling the urge to use my smartphone again right after I stopped using it.,"Having tried time and again to shorten my smartphone use time, but failing all the time.",Always thinking that I should shorten my smartphone use time.,The people around me tell me that I use my smartphone too much.
0,sub002,1,1,2,1,2,1,2,5,1,...,2,1,1,5.0,2.0,2,2,1,2,1
1,sub003,5,4,4,3,5,5,4,4,4,...,4,5,2,4.0,5.0,5,5,5,5,3
2,sub004,1,4,4,4,2,5,5,5,4,...,4,1,2,6.0,3.0,2,4,2,2,4
3,sub005,6,6,3,5,4,5,5,5,5,...,2,2,2,5.0,2.0,5,2,6,5,2
4,sub006,1,1,3,2,3,3,4,3,2,...,1,3,1,3.0,1.0,3,2,1,3,2

In [137]:

sas_response_dict = {'participant_id' : "BIDS participant identifier"}
for i ,qus in enumerate(sas_response.columns):
    if i >0 : 
        qus_num = "Q"+str(i)
        sas_response_dict[qus_num]= qus
sas_response_dict
list_slice = list(sas_response_dict.items())[1:]
sliced_dict = dict(list(sas_response_dict.items())[1:])
print(sliced_dict)
# Swap keys and values
swapped_dict = {v: k for k, v in sliced_dict.items()}

# Display the swapped dictionary
print(swapped_dict)
sas_response.rename(columns=swapped_dict,inplace=True)
sas_response.head()

{'Q1': 'Missing planned work due to smartphone use.', 'Q2': 'Having a hard time concentrating in class, while doing assignments, or while working due to smartphone use.', 'Q3': 'Experiencing lightheadedness or blurred vision due to excessive smartphone use.', 'Q4': 'Feeling pain in the wrists or at the back of the neck while using a smartphone.', 'Q5': 'Feeling tired and lacking adequate sleep due to excessive smartphone use.', 'Q6': 'Feeling calm or cozy while using a smartphone.', 'Q7': 'Feeling pleasant or excited while using a smartphone.', 'Q8': 'Feeling confident while using a smartphone.', 'Q9': 'Being able to get rid of stress with a smartphone.', 'Q10': 'There is nothing more fun to do than using my smartphone.', 'Q11': 'My life would be empty without my smartphone. ', 'Q12': 'Feeling most liberal while using a smartphone.', 'Q13': 'Using a smartphone is the most fun thing to do. ', 'Q14': 'Won’t be able to stand not having a smartphone.', 'Q15': 'Feeling impatient and fretful when I am not holding my smartphone.', 'Q16': 'Having my smartphone in my mind even when I am not using it.', 'Q17': 'I will never give up using my smartphone even when my daily life is already greatly affected\nby it.', 'Q18': 'Getting irritated when bothered while using my smartphone.', 'Q19': 'Bringing my smartphone to the toilet even when I am in a hurry to get there.', 'Q20': 'Feeling great meeting more people via smartphone use.', 'Q21': 'Feeling that my relationships with my smartphone buddies are more intimate than my\nrelationships with my real-life friends.', 'Q22': 'Not being able to use my smartphone would be as painful as losing a friend.', 'Q23': 'Feeling that my smartphone buddies understand me better than my real-life friends.', 'Q24': 'Constantly checking my smartphone so as not to miss conversations between other people\non Twitter or Facebook.', 'Q25': 'Checking SNS (Social Networking Service) sites like Twitter or Facebook right after waking up.', 'Q26': 'Preferring talking with my smartphone buddies to hanging out with my real-life friends or\nwith the other members of my family.', 'Q27': 'Preferring searching from my smartphone to asking other people.', 'Q28': 'My fully charged battery does not last for one whole day.', 'Q29': 'Using my smartphone longer than I had intended.', 'Q30': 'Feeling the urge to use my smartphone again right after I stopped using it.', 'Q31': 'Having tried time and again to shorten my smartphone use time, but failing all the time.', 'Q32': 'Always thinking that I should shorten my smartphone use time.', 'Q33': 'The people around me tell me that I use my smartphone too much.'}
{'Missing planned work due to smartphone use.': 'Q1', 'Having a hard time concentrating in class, while doing assignments, or while working due to smartphone use.': 'Q2', 'Experiencing lightheadedness or blurred vision due to excessive smartphone use.': 'Q3', 'Feeling pain in the wrists or at the back of the neck while using a smartphone.': 'Q4', 'Feeling tired and lacking adequate sleep due to excessive smartphone use.': 'Q5', 'Feeling calm or cozy while using a smartphone.': 'Q6', 'Feeling pleasant or excited while using a smartphone.': 'Q7', 'Feeling confident while using a smartphone.': 'Q8', 'Being able to get rid of stress with a smartphone.': 'Q9', 'There is nothing more fun to do than using my smartphone.': 'Q10', 'My life would be empty without my smartphone. ': 'Q11', 'Feeling most liberal while using a smartphone.': 'Q12', 'Using a smartphone is the most fun thing to do. ': 'Q13', 'Won’t be able to stand not having a smartphone.': 'Q14', 'Feeling impatient and fretful when I am not holding my smartphone.': 'Q15', 'Having my smartphone in my mind even when I am not using it.': 'Q16', 'I will never give up using my smartphone even when my daily life is already greatly affected\nby it.': 'Q17', 'Getting irritated when bothered while using my smartphone.': 'Q18', 'Bringing my smartphone to the toilet even when I am in a hurry to get there.': 'Q19', 'Feeling great meeting more people via smartphone use.': 'Q20', 'Feeling that my relationships with my smartphone buddies are more intimate than my\nrelationships with my real-life friends.': 'Q21', 'Not being able to use my smartphone would be as painful as losing a friend.': 'Q22', 'Feeling that my smartphone buddies understand me better than my real-life friends.': 'Q23', 'Constantly checking my smartphone so as not to miss conversations between other people\non Twitter or Facebook.': 'Q24', 'Checking SNS (Social Networking Service) sites like Twitter or Facebook right after waking up.': 'Q25', 'Preferring talking with my smartphone buddies to hanging out with my real-life friends or\nwith the other members of my family.': 'Q26', 'Preferring searching from my smartphone to asking other people.': 'Q27', 'My fully charged battery does not last for one whole day.': 'Q28', 'Using my smartphone longer than I had intended.': 'Q29', 'Feeling the urge to use my smartphone again right after I stopped using it.': 'Q30', 'Having tried time and again to shorten my smartphone use time, but failing all the time.': 'Q31', 'Always thinking that I should shorten my smartphone use time.': 'Q32', 'The people around me tell me that I use my smartphone too much.': 'Q33'}

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\1933412895.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sas_response.rename(columns=swapped_dict,inplace=True)

,participant_id,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,...,Q24,Q25,Q26,Q27,Q28,Q29,Q30,Q31,Q32,Q33
0,sub002,1,1,2,1,2,1,2,5,1,...,2,1,1,5.0,2.0,2,2,1,2,1
1,sub003,5,4,4,3,5,5,4,4,4,...,4,5,2,4.0,5.0,5,5,5,5,3
2,sub004,1,4,4,4,2,5,5,5,4,...,4,1,2,6.0,3.0,2,4,2,2,4
3,sub005,6,6,3,5,4,5,5,5,5,...,2,2,2,5.0,2.0,5,2,6,5,2
4,sub006,1,1,3,2,3,3,4,3,2,...,1,3,1,3.0,1.0,3,2,1,3,2

In [138]:
# Create BIDS dataset directory if it doesn't exist
os.makedirs(r'D:\Work_data\Notification_evoked_response\Data_at_IITD/bids_data/phenotype/', exist_ok=True)
#  save it as a TSV file (tab-separated)
sas_response.to_csv(r'D:\Work_data\Notification_evoked_response\Data_at_IITD/bids_data/phenotype/sas_responses.tsv', sep='\t', index=False)
# Save the dictionary as a JSON file
with open(r'D:\Work_data\Notification_evoked_response\Data_at_IITD/bids_data/phenotype/sas_responses.json', 'w') as json_file:
    json.dump(sas_response_dict, json_file, indent=4)

,participant_id,How much do you agree with the statement: I am addicted to my smartphone?,My phone is on [Silent / DND],My phone is on [Vibrate only],My phone is on [Loud],Do you receive notifications on some other device instead (like a smartwatch)?,What emotions are typically associated with receiving smartphone notifications?,How did you feel about the notifications during the first half of the experiment?,How did you feel about the notifications during the 2nd half of the experiment?,MPPUS
0,sub002,Disagree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0
1,sub003,Strongly agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176.0
2,sub004,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,124.0
3,sub005,Disagree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,140.0
4,sub006,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.0

In [147]:

oth_response  = combined_df.iloc[:, [0] + list(range(61, 69))]
oth_response.head()

oth_response_dict = {'participant_id' : "BIDS participant identifier"}
for i ,qus in enumerate(oth_response.columns):
    if i >0 : 
        qus_num = "Q"+str(i)
        oth_response_dict[qus_num]= qus
oth_response_dict
list_slice = list(oth_response_dict.items())[1:]
sliced_dict = dict(list(oth_response_dict.items())[1:])
print(sliced_dict)
# Swap keys and values
swapped_dict = {v: k for k, v in sliced_dict.items()}

# Display the swapped dictionary
print(swapped_dict)
oth_response.rename(columns=swapped_dict,inplace=True)
oth_response.head()

{'Q1': 'How much do you agree with the statement: I am addicted to my smartphone?', 'Q2': 'My phone is on [Silent / DND]', 'Q3': 'My phone is on [Vibrate only]', 'Q4': 'My phone is on [Loud]', 'Q5': 'Do you receive notifications on some other device instead (like a smartwatch)?', 'Q6': 'What emotions are typically associated with receiving smartphone notifications?', 'Q7': 'How did you feel about the notifications during the first half of the experiment?', 'Q8': 'How did you feel about the notifications during the 2nd half of the experiment?'}
{'How much do you agree with the statement: I am addicted to my smartphone?': 'Q1', 'My phone is on [Silent / DND]': 'Q2', 'My phone is on [Vibrate only]': 'Q3', 'My phone is on [Loud]': 'Q4', 'Do you receive notifications on some other device instead (like a smartwatch)?': 'Q5', 'What emotions are typically associated with receiving smartphone notifications?': 'Q6', 'How did you feel about the notifications during the first half of the experiment?': 'Q7', 'How did you feel about the notifications during the 2nd half of the experiment?': 'Q8'}

C:\Users\PRAKASH\AppData\Local\Temp\ipykernel_9876\1144340842.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oth_response.rename(columns=swapped_dict,inplace=True)

  participant_id              Q1   Q2   Q3   Q4   Q5   Q6  Q7  Q8
0         sub002        Disagree  NaN  NaN  NaN  NaN  NaN NaN NaN
1         sub003  Strongly agree  NaN  NaN  NaN  NaN  NaN NaN NaN
2         sub004         Neutral  NaN  NaN  NaN  NaN  NaN NaN NaN
3         sub005        Disagree  NaN  NaN  NaN  NaN  NaN NaN NaN
4         sub006           Agree  NaN  NaN  NaN  NaN  NaN NaN NaN

In [148]:
#  save it as a TSV file (tab-separated)
oth_response.to_csv(r'D:\Work_data\Notification_evoked_response\Data_at_IITD/bids_data/phenotype/other_responses.tsv', sep='\t', index=False)
# Save the dictionary as a JSON file
with open(r'D:\Work_data\Notification_evoked_response\Data_at_IITD/bids_data/phenotype/other_responses.json', 'w') as json_file:
    json.dump(oth_response_dict, json_file, indent=4)